// Generated by ReScript, PLEASE EDIT WITH CARE

import Link from "next/link";
import * as JsxRuntime from "react/jsx-runtime";

function Navbar$Navigation(props) {
  return JsxRuntime.jsxs("nav", {
              children: [
                JsxRuntime.jsx(Link, {
                      href: "/",
                      children: JsxRuntime.jsx("img", {
                            className: "w-16 h-16",
                            alt: "Lambda-Engine",
                            src: "static/Lambda-Calculus-No-Bg.gif"
                          })
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(Link, {
                              href: "/blog",
                              children: "Blog"
                            }),
                        JsxRuntime.jsx(Link, {
                              href: "/portifolio",
                              children: "Portifolio"
                            }),
                        JsxRuntime.jsx(Link, {
                              href: "/about",
                              children: "About"
                            })
                      ],
                      className: "flex flex-row gap-6 justify-between items-center"
                    })
              ],
              className: "h-24 flex justify-between items-center text-sm text-white rounded shadow-white ml-20 mr-20"
            });
}

var $$Navigation = {
  make: Navbar$Navigation
};

var Link$1;

export {
  Link$1 as Link,
  $$Navigation ,
}
/* next/link Not a pure module */
